import type { Metadata } from "next";

import "./globals.css";
import Provider from "./provider"
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Provider>
        <Navbar/>
        {children}
        <Footer/>
      </Provider>
      </body>
    </html>
  );
}
